### ISSUE TITLE
oAuth extension failed on phpBB 3.1.12

### ISSUE THREAD

**Issue by zagura** [iiet/phpbb-oauth#1]
Entering forum site, I am not redirected to accounts login page. Instead of that, I can log in with db user and password.
On admin panel, Auth subpage throw 500 with log:
```
[error] 20036#20036: *2704 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 9 passed to phpbb\auth\provider\oauth\oauth::__construct() must be an instance of phpbb\di\service_collection, string given, called in /var/www/forum/public/public_html/cache/production/container_dbdbe80dc7030ae9bd39ee30cca82130.php on line 537 and defined in /var/www/forum/public/public_html/phpbb/auth/provider/oauth/oauth.php:146
Stack trace:
#0 /var/www/forum/public/public_html/cache/production/container_dbdbe80dc7030ae9bd39ee30cca82130.php(537): phpbb\auth\provider\oauth\oauth->__construct(Object(phpbb\db\driver\factory), Object(phpbb\config\db), Object(phpbb\passwords\manager), Object(phpbb\request\request), Object(phpbb\user), 'phpbb_oauth_tok...', 'phpbb_oauth_acc...', Object(phpbb\di\service_collection), 'phpbb_users', Object(phpbb_cache_container), './../', 'php')
#1 /var/www/forum/public/public_html/vendor/symfony/dependency-injection/Container.php(297): phpbb_cache_container->getAuth_Provider_OauthIietService()
```

**Comment by zagura** [comment]
Additional search showed that it could be introduced in phpBB 3.1.12 with those code changes.
https://area51.phpbb.com/code-changes/3.1.10/side-by-side/3.1.12/phpbb-phpbb-auth-provider-oauth-oauth.php.html
